version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    environment:
      BUCKET_ACCESS_KEY_ID: $BUCKET_ACCESS_KEY_ID
      BUCKET_SECRET_ACCESS_KEY: $BUCKET_SECRET_ACCESS_KEY
      BUCKET_NAME: $BUCKET_NAME
      BUCKET_ENDPOINT_URL: $BUCKET_ENDPOINT_URL
      BUCKET_REGION: $BUCKET_REGION
      RUNPOD_API_TOKEN: $RUNPOD_API_TOKEN
      RUNPOD_API_ENDPOINT: $RUNPOD_API_ENDPOINT
    command: ["npx","vite","--host","0.0.0.0"]

volumes:
  data:
