version: '3.8'

services: #For some reasons, pulling from docker-compose doesn't work
  app:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      MINIO_BUCKET_NAME: $MINIO_BUCKET_NAME
      MINIO_SERVER_URL: $MINIO_SERVER_URL
      MINIO_REGION: $MINIO_REGION
    command: ["npx","vite","--host","0.0.0.0"]


  minio:
    image: minio/minio
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"  # Adding console port as well
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_SERVER_URL: $MINIO_SERVER_URL
    command: server /data --console-address ":9001"  # Specifying console address

volumes:
  data:
