version: '3.8'

services: #For some reasons, pulling from docker-compose doesn't work
  app: 
    image: node:16
    user: "${UID}:${GID}"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npx","vite","--host","0.0.0.0"]


  minio:
    image: minio/minio
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"  # Adding console port as well
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      MINIO_SERVER_URL: http://localhost:9000  # Explicitly setting the server URL
    command: server /data --console-address ":9001"  # Specifying console address

volumes:
  data:
